### ISSUE TITLE
Viewing campaign cinematics and transmission logs

### ISSUE THREAD

**Issue by mirddes** [FAForever/fa-coop#102]
https://www.reddit.com/r/supremecommander/comments/wh9ysq/did_they_remove_transmission_logs_from_supcom_fa/
![image](https://user-images.githubusercontent.com/13982888/183963845-0eda0f7c-e3a2-4b2d-b8c9-1dde528d777f.png)

Currently, anyone wishing to experience the complete supreme commander/FA campaign experience must play it without FAF.

A way to view all cinematics associated with each campaign mission from within the FAF client would be awesome.

Directly from the gamefiles of course, i link below to all of the cinematics in case anyone has forgotten how awesome they are.

Almost as awesome as everyone who contributes to FAF, thank you all.

https://www.youtube.com/watch?v=gFww4ZzbuzI
https://www.youtube.com/watch?v=ya75D2oil9A
https://www.youtube.com/watch?v=XccOF8b9SHg
https://www.youtube.com/watch?v=hpt6ddV-Tl8

**Comment by mirddes** [comment]
i still think this is a cool idea.

**Comment by Garanas** [comment]
Not intended - these videos are from the special campaign menu and it would require a lot of adjustments to add these in.

**Comment by mirddes** [comment]
Fair enough, tbh about what I expected.

It would be undeniably cool though right?

Thank you for the reply
I hope you are well
Have an amazing day :D

**Comment by speed2CZ** [comment]
It would be cool
