### ISSUE TITLE
FakeTeleportUnit doesn't work

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#12]
ScenarioFramework.FakeTeleportUnit(ScenarioInfo.SeraACU, true)

This function doesn't work anymore, its not teleporting units. It is used for AI ACU's to escape before you kill them or forciv trucks you need to get to quantum gate to escape planet. The unit will not telelport, giving this warning:

WARNING: Error running lua script: ...data\faforever\gamedata\lua.nx2\lua\system\utils.lua(45): attempt to loop over local `t' (a nil value)
         stack traceback:
            ...data\faforever\gamedata\lua.nx2\lua\system\utils.lua(45): in function`copy'
            ...a\faforever\gamedata\lua.nx2\lua\effectutilities.lua(1546): in function `TeleportLocationToSurface'
            ...a\faforever\gamedata\lua.nx2\lua\effectutilities.lua(1370): in function`PlayTeleportChargingEffects'
            ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3809): in function `PlayTeleportChargeEffects'
            ...faforever\gamedata\lua.nx2\lua\scenarioframework.lua(843): in function`FakeTeleportUnit'
            ...orged alliance\maps\prothyon16\prothyon16_script.lua(1651): in function <...orged alliance\maps\prothyon16\prothyon16_script.lua:1650>

**Comment by Washeh** [comment]
https://github.com/FAForever/fa/blob/develop/lua/ScenarioFramework.lua#L843
the function does not pass the required parameter for
https://github.com/FAForever/fa/blob/develop/lua/sim/Unit.lua#L3784
(despite orientation is not used, and location is probably always the unit position)
