### ISSUE TITLE
Allied AI shares resources

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#13]
Sharing resources from Allied AIs need to be removed.

**Comment by Sheeo** [comment]
Why? :)

**Comment by speed2CZ** [comment]
1. \- Cause AI can't use eco well and its sharing energy that it shouldn't. Missions where you have AI from the beginning you don't need to care about T1 T2 pgens, go straight for RAS. 
2. \- It was never in campaign and I think it is not improving gameplay for player.
3. \- I got assigned for balancing coop missions and I decided to not have this feature.
4. \- Blame Gorton

**Comment by theeggroll** [comment]
Map specific fa mission 3 is eZ cuz RAS right away and then you dont need to make resouces for like 10 minutes

**Comment by ChrisKitching** [comment]
This must have been particularly hilarious when the AI had infinite resources.

**Comment by speed2CZ** [comment]
it wasnt, cause until this coop update AI didnt share anything, its allowed since the update, when rewriting coop you might have miss this part that disabled sharing resources from AI

**Comment by speed2CZ** [comment]
Closed this by some accident before fix is actually deployed

**Comment by speed2CZ** [comment]
Fixed by https://github.com/FAForever/faf-coop-maps/commit/f6b2d0b5e5aca916162d7f7fb58f121aa8caf37a
