### ISSUE TITLE
When player ACU dies the game does not end

### ISSUE THREAD

**Issue by theeggroll** [FAForever/fa-coop#15]
Logs
https://gist.github.com/theeggroll/91d2fa022cee559a345c
https://gist.github.com/theeggroll/e15f5e412208a3c95976

2nd player (couldnt find game)
https://gist.github.com/anonymous/ce54124b7a9485a37bd7

3rd player (also couldnt find game
https://gist.github.com/anonymous/15210446a07d2ace9830

**Comment by ChrisKitching** [comment]
Fixed with https://github.com/FAForever/faf-coop-maps/commit/4dedaedf98d6b11c77d1782c4a451f8dbea9ba9a and 91496d6a9570c43dc3fea993504c4dd5982c255e
