### ISSUE TITLE
Unban Seraphim

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#19]
http://forums.faforever.com/forums/viewtopic.php?f=42&t=10622

There isnt really a need to ban mods that allow seraphim in campaign. Let people have fun, If you are worried about leaderboard times, it would be better to make them count only unmodded games. Since this isnt the only mod that could give any kind of advantage.

**Comment by ChrisKitching** [comment]
> There isnt really a need to ban mods that allow seraphim in campaign.

It is definitely not the case that "we ban mods that allow seraphim in campaign".

We simply don't have the seraphim in the unmodded version of the campaign, for the reasons I explained at length on the forum thread you linked.

We already don't rank modded games. The community is more than welcome to write a mod that does this and have as much hilarious and buggy campaign madness as they like.

**Comment by speed2CZ** [comment]
LOL, no one is gonna report that his mod that allows seraphim in campaign doesnt work well. There are many more mods that adds new units and those units wont be restricted in campaign. But you just decided to ban those mods that allows to play seraphim just because. You dont have a single valid reason. With your logic you would have to ban all the mods from coop.

**Comment by Sheeo** [comment]
@speed2CZ Seraphim isn't banned, it's just not officially supported.

If you want it supported you should do this yourself and fix the unit restrictions. For bonus points introduce a fallback VO.
