### ISSUE TITLE
Improve loading of coop mod

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa-coop#2]
I'm struggling to understand A: How this system works and B: Which files are actually necessary.

I've tried modifying the appropriate file by copying in all the files from the main FAF develop branch, while leaving all the existing Coop branch files intact (With the exceptions of the LOC file, unit.lua, Projectiles, and Units), so to my mind it _Should_ work unless something silly is going on.

Oddly, the error I get is that there is no starting location defined for the Armies in the campaign maps! Which is really odd, because there definitely is, I've checked. Somewhere, possibly in some lobby code, something's gone wrong :/

**Comment by Eximius** [comment]
You are correct, coop is just loaded on top of main faf with a init.lua script. So having all the files copied over should work in theory, though instead, just make an init.lua script that first loads up FAF develop then FAF coop and it should work. Fewer things to explode.

**Comment by Sheeo** [comment]
The way it works seems to be a bit more involved:
- lobby_coop.cop is generated from the state in _this_ repo, containing just the files that differ from main faf.
- _.cop files are insterted into the game path *before_ .nxt, .nx2 and .scd files.

This is causing issues. It should be fixed with new-patcher where we do init file generation. This repository needs to be ripped apart into a mod of its own, that will hook into the files that it needs to change.

Is anyone up for this?

**Comment by aeoncleanse** [comment]
I kinda did this already...

My merge branch is just develop + files from this repo which are new to the lua repo + a couple of bare minimum changes to existing files needed to get it to recognise and launch coop maps, and then it's all good. The rest of the entire diff between this repo and lua repo are unnecessary bloat and/or outdated code.

**Comment by Sheeo** [comment]
What I'd like is a repository with just the files that coop needs to have changed, with the minimum changes as hooks instead. Would you be willing to do this?

**Comment by aeoncleanse** [comment]
Sure thing, shouldn't be much work at all. Not sure I can do it as hooks but I'll give it a shot. I can't test it as a mod though, because some changes are to lobby. In fact, all of them are.

Personally I don't see why we need this as an alternative mode one bit. Just let people load and play the maps the way they would any other... Much easier, much simpler.

**Comment by Sheeo** [comment]
You can test it if you Zip the mod files into a zip file, and insert this into your game path before faf and other files are loaded.

The lobby can be hooked into as well, if done that way.
