### ISSUE TITLE
Remove Reclaim/Repair from Harbingers

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#29]
Harbingers put on patrol or attack move just reclaim/repair everything in their way instead of attacking.
Better to remove these abilities.

@Crotalus can you help with this?

**Comment by aeoncleanse** [comment]
Reclaim is a core part of Harb functionality. Pretty sure it won't be removed.

**Comment by speed2CZ** [comment]
This is coop go away

I can think of a solution, removing reclaim, repair feom harbs. Restricting harbs for human players. Adding unit with new ID which is copy pasted harbinger with reclaim, repair.

Unless someone knows to to make AI actually attack with harbs instead of pretending to be an engineer on a reclaim mission.
Better @aeoncleanse

**Comment by Garanas** [comment]
Resolved with https://github.com/FAForever/fa/pull/4225 and https://github.com/FAForever/FA-Binary-Patches/pull/13.
