### ISSUE TITLE
Glitches/bad-stuff in campaign missions

### ISSUE THREAD

**Issue by theeggroll** [FAForever/fa-coop#3]
An overall glitch that happens in all Vanilla missions is that when air units die in water, they don't change into wrecks, they even continue to have fuel lines and look as though they are still in the air.

I havent done much testing for this one, but I got personal shield on my commander in a co op mission (uef level 4) and it didnt take damage. 

A feature that is missing from campaign replays is the ability to speed up the game, kind of a pain sometimes if you're looking for something that happened an hour into a game.

Uef Vanilla Campaign:
Mission 2: I played through it several times, one time after repairing the science facility and then taking out the Aeon patrols, nothing happened for 10 minutes and I gave up. (There is supposed to be multiple attacks on the science facitlity in waves) (replay 2898001)
Mission 3: Same thing as mission two, after colonel arnold goes boom and the aeon counter attack waves are supposed to come in, only one wave came and then I sat there and eco'd for about 10 minutes and nothing else came so I quit. (replay 2880936)
Mission 6: Whenever shields go down they dont auto matically reboot. You have to manually turn them off and then back on.

No bugs discovered for Cybran campaign as of yet, although there really arent very many missions to play :(

Same for Aeon missions, I'm going to play them through soon.

Fa campaign missions:
Level 4: This mission is nearly impossible with one person playing. I played it 6 or 7 times and wasnt able to get my foot in the door. In the non-faf version of this mission, there is a destroyed t3 UEF base right where you spawn, and therefore you can eco VERY quickly and can be ready for Ilshovahs in a couple minutes, however in the faf version of the mission there is no base at all to reclaim, and therefore when Ilshovahs come after a couple minutes you get eaten alive.

More to come in the future, I'll add more as I find it
-theeggroll

**Comment by aeoncleanse** [comment]
I can't speak for everyone else, but personally I want to get rid of coop 'mode' and just let the lobby allow people to play the maps. It will kill all these bugs, allow us to test and improve the maps more easily, and just seems more streamlined than the current system.

Mission 4 is tough but not impossible. Try to use your ACU as much as possible, OC like a bastard, and get T2 and Shields ASAP. Then it's easy peasy.

**Comment by theeggroll** [comment]
aeoncleanse, you cant have your acu OC'ing the ilshovahs north AND south of your base at the same time, also campaign missions are supposed to be playable/beatable by anyone, and level 4 is hard as shit
I don't necissarily want co op to be able to work, I just want all the missions to work like they're supposed to. hence the bug report

**Comment by aeoncleanse** [comment]
Bug report is absolutely noted, and will be fixed in time, but I can't see us doing anything about difficulty. I'm 1100 rating, below average and a poor player, and I can consistently beat the mission so it's not that hard.

**Comment by VoRGoR** [comment]
All the campaign missions are sadly beaten by repetition - i.e knowing what's going to come and then reacting to it before it happens. 
It's difficult but only the first time you do it because the next time you know what's coming.

**Comment by theeggroll** [comment]
I must really suck then XD I can beat mission 4 on non-faf like its no big deal, but I get fucked in the faf every time (im rated at 1000)

Nothing about difficulty needs to be done, you just need to go into the map and add the t3 uef base wrecks. With those the mission would be easy again

**Comment by MattDeering** [comment]
FA mission 4 USED to have a whole ton of reclaim, then suddenly the map version was updated and it was all gone. Not sure exactly when it happened.

**Comment by GZcodingteam** [comment]
I just beat level 4 faf, I'm only rated 383.

**Comment by ChrisKitching** [comment]
> An overall glitch that happens in all Vanilla missions is that when air units die in water, they don't change into wrecks, they even continue to have fuel lines and look as though they are still in the air.
> 
> I havent done much testing for this one, but I got personal shield on my commander in a co op mission (uef level 4) and it didnt take damage.
> 
> A feature that is missing from campaign replays is the ability to speed up the game, kind of a pain sometimes if you're looking for something that happened an hour into a game.

Coop used to force the use of a much older (and buggier) version of FAF. These all sound like bugs in that ancient FAF, which should now have gone away, since coop now works with current FAF.

> No bugs discovered for Cybran campaign as of yet, although there really arent very many missions to play :(

The last three are, I think, now up. I have no idea how broken they are: the general theme is probably "very".

**Comment by MattDeering** [comment]
Eggroll and I have posted issues regarding last 3 cybran missions already.

**Comment by theeggroll** [comment]
This was posted 8 months ago XD current bug reports are being submitted by Derring and I a few times per week

**Comment by speed2CZ** [comment]
lets close this
