### ISSUE TITLE
SharedUnitCap doesn't recalculate when player dies

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#57]
https://github.com/FAForever/fa-coop/blob/master/mods/coop/hook/lua/ScenarioFramework.lua#L65-L70

Not all missions fail when one player dies/quits, would be nice to share his unit cap to the others.

**Comment by TheKeyBlue** [comment]
Guess we should hook this function?
https://github.com/FAForever/fa/blob/6bfdf7f04f5fd3a09d02884d68dc4d68a1a54666/lua/SimUtils.lua#L217

and set the ShareUnitCap lobbyoption to 'all' by default?
Maybe even remove the possibility to choose unitcap yourself?

**Comment by speed2CZ** [comment]
Yes, that sounds good,
Only thing Im not sure is `ScenarioInfo.Options.UnitCap` which will be probably different from what you set in the mission script, so need to count with that and include it into `SetSharedUnitCap` function is needed.

**Comment by speed2CZ** [comment]
get inspired here https://github.com/FAForever/fa/blob/develop/lua/SimUtils.lua#L217
