### ISSUE TITLE
Repeating warning in log

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#6]
After one of the recent updates of coop, log is spammed with this warning, I guess everytime any shield is spawned or built
WARNING: Deprecated function unit:OnShieldEnabled() called
and this one everytime shield goes down
WARNING: Deprecated function unit:OnShieldDisabled() called

**Comment by aeoncleanse** [comment]
Yup, this has been addressed in the next patch :)

**Comment by ChrisKitching** [comment]
A shortlived regression in fa/release/3641.
