### ISSUE TITLE
Implement Bonus / Hidden Objectives

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#60]
There used to be a plan to have bonus objectives in the missions. My plan is to introduce these together with the achievements.
They would be hidden until you complete them.

So new type `'bonus'` must be implemented here https://github.com/FAForever/fa/blob/develop/lua/SimObjectives.lua
and might need to do changes on the UI side as well to not list the objectives.

**Comment by micheljung** [comment]
Had a quick look at your document, I like the idea!

**Comment by speed2CZ** [comment]
Implemented, now the objectives just have to be added into the misisons
