### ISSUE TITLE
Wrong voice cues

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#69]
Few slipped through and the missions have swapped some of the voice cues.
- [x] A05 - princess
- [x] E04 - clarke
- [x] Prothyon

**Comment by PhilipJFryFAF** [comment]
Prothyon:
Gyles lines after the destruction of the UEF island base are missing.
Morax's lines in the same mission are also missing.
Johnson complaines about trucks being destroyed instead of instructing you to get them to savety.
Morax plays the voice line for being low on HP when gating out.
