### ISSUE TITLE
Audio Issues

### ISSUE THREAD

**Issue by MattDeering** [FAForever/fa-coop#8]
Audio from the objective updates/taunts etc is broken, since its in a range of maps it might be a coop thing

https://gist.github.com/MattDeering/dfc86ac4b2bedbbd13fb
https://gist.github.com/MattDeering/f15b4c994740f63a9569
https://gist.github.com/MattDeering/440cb0efdef662afdb16

https://gist.github.com/theeggroll/928d839a08b4b0b04493
https://gist.github.com/theeggroll/4de5c3300ba0d719d4cd

**Comment by theeggroll** [comment]
Game where Audio worked for Deering and not for me
https://gist.github.com/theeggroll/167f8cfd5f2b488ad8e6
https://gist.github.com/theeggroll/86d6c0cdd16c26180328
Deering:
https://gist.github.com/MattDeering/d87e073d1ebd02b202ce
https://gist.github.com/MattDeering/a1ca84b299c993313eac

**Comment by ChrisKitching** [comment]
I think we expect this from SC1 maps if you haven't linked your SC1 install to the FAF client. FA doesn't ship the voice-overs and whatnot for the SC1 campaign, so if you don't link your install there's no way to find those assets.

I'm also not hugely confident that that the client's implementation of the linking is sane, but it's our best shot :P

**Comment by MattDeering** [comment]
Pretty sure I do have it linked. If you don't have it linked the videos don't work but the sound did. The sound still did though. There was someone who converted it from vanilla to Fa format. Complex and someone else I think. Will look into it more when I get home on sunday

**Comment by theeggroll** [comment]
I have it linked for sure and Deering does as well, before the update you'd permanently desync if you played with someone who doesn't have it linked and you do, and Deering and I were able to play.

**Comment by speed2CZ** [comment]
linking vanilla is just for getting videos to work, sound files were on FAF server and got downloaded into this folder: C:\ProgramData\FAForever\extra\sounds\voice\us
Problem is that after the coop update they wont get downloaded, but if no one deleted them, they should still be there.

**Comment by speed2CZ** [comment]
Voices should work everywhere now
