### ISSUE TITLE
Increase ACU Death Nuke Damage

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa-coop#80]
Since we are in coop we can make the ACU deal a real damage that kills buildings. Maybe not full Nuke but much more that the current one. It's not like there would be much ACU on ACU combat resulting in a draw.

**Comment by Garanas** [comment]
All fine to me - this is co-op after all. Things are allowed to be different from standard gameplay.

**Comment by speed2CZ** [comment]
https://github.com/FAForever/fa-coop/pull/101
