### ISSUE TITLE
Mods not autoloading in coop games

### ISSUE THREAD

**Issue by Franck83** [FAForever/fa-coop#85]
Hi dear devs,

Fa-coop is a fantastic faf feature. 

Players need to manually download mods to join coop-games. Only 30% do it. Some try to join several times what means that they don't know how to use mod vault.

Ty for fixing this issue.

**Comment by speed2CZ** [comment]
That doesnt look like an issue with the mod. Its not touching any part that would be sending enabled mod list to the server or so.
So its either client or server or whatnot (dunno how exactly this works)

**Comment by ChrisKitching** [comment]
Yeah, this is a client bug.
