### ISSUE TITLE
AI - AI Teams won't build new bases or replace buildings due to case sensitivity

### ISSUE THREAD

**Issue by JJ173-zz** [FAForever/fa-coop#90]
Found an issue the other day with the AI portion of campaign. 

I was using Ozone's new editor to make a new mission and found that his editor saves unit IDs in upper case. (E.G UEL0001 instead of uel0001). 

This causes an issue with the AI which means they will break to a point where they cannot build new bases or replace existing buildings as the AI only works with lower case unit IDs. 

When I spawned a new AI team to build a base, they stood idle as they could not use the IDs of buildings that were saved in upper case. They only started assiting factories that I placed personally either using cheats or taking control of their ACU. 

I will submit a bug with Ozone as well to get him to make sure the units are saved in lower case. However, I think the AI code should be case insensitive for this logic.

**Comment by speed2CZ** [comment]
not coop issue, but editor issue. Everyting in Lua is case sensitive

**Comment by ozonexo3** [comment]
Fixed in FAF Map Editor v0.606 WIP9
