### ISSUE TITLE
Allow custom props, units, emitters to be loaded from the co-op map folder

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa-coop#95]
This isn't something we want for the typical game due to ensuring that props are similar across maps. However, for campaign maps I see no reason why we would not allow developers to essentially make a mod inside their map that can change / add everything a campaign maker would want. Marlo (one of the campaign makers) is particularly interested in this.
 - [ ] Allow for a hooks folder for scripts.
 - [ ] Allow for a units folder to create / merge unit blueprints.
 - [ ] Allow for an env folder to create / merge prop blueprints.
 - [ ] Allow for an effect folder to create / merge emitter blueprints.
 - [ ] Allow for a sound folder to create sound / music.
 - [ ] Allow for a video folder to create video.

This would require a change to the init file - I'll make a PR later this week. @Crotalus I do not have write access here, but what are your thoughts on this?

**Comment by speed2CZ** [comment]
Good reason to not have it to reduce the data you have to download with new versions, especially movies and sounds, as they rarely change.

**Comment by Garanas** [comment]
That is quite true - could you make an estimation as to how often that would happen? Updating a mission?

**Comment by speed2CZ** [comment]
If its new mission, then probably quite often, else https://github.com/FAForever/faf-coop-maps/releases

**Comment by Sheikah45** [comment]
Just as an FYI the downloading of the sounds and movies each time should stop going forward now that the deployment from the api has been fixed. As long as nothing in those folders has changed.

**Comment by Sheikah45** [comment]
Generally I do think this is a good idea. As most of the common converns regarding things like cheat maps/props or non compatible maps will not apply to the coop scenario.

**Comment by speed2CZ** [comment]
Does that work for maps as well?

**Comment by Sheikah45** [comment]
Hmm for maps it might not though. I thought that was regarding the coop mod. With regards to the file size of the maps themselves, I would not personally be overly worried about those file sizes. 
If you really wanted to mitigate it then the option would be to just not include video or sound as I would imagine that would be the bulk of the space. But I don't know if that is a big enough factor to remove the ability for people to make full campaign maps.

**Comment by Sheikah45** [comment]
I would compare it to some of the larger mods we have in the vault

**Comment by speed2CZ** [comment]
Sounds are videos were exactly for that reason removed from maps and are separate, It's not stopping anyone from making it and it's supported, but it should just not be in the map files

**Comment by Sheikah45** [comment]
Yeah then if there is a separate place for sounds and videos then just don't mount those and use the common place. The rest of this I think is fine.

**Comment by Garanas** [comment]
Where is that separate place?

**Comment by speed2CZ** [comment]
Zipped mission video files are uploaded to the git released and server script that updates coop can take them from there.
